apps/post/urls.py
from django.urls import path

from .views import (
    CustomLoginView,
    CustomLogoutView,
    WelcomePageView,
    PostToTwitter,
    TwitterLogin,
    twitter_login_sso,
    twitter_callback_sso,
    AboutUsView,
    health_check
)

app_name = 'apps.post'

urlpatterns = [
    path('', WelcomePageView.as_view(), name='welcome_page'),
    path('post-to-twitter/', PostToTwitter.as_view(), name='post_to_twitter'),
    path('login/', TwitterLogin.as_view(), name='login'),
    path('twitter-login', twitter_login_sso, name='twitter_login'),
    path('callback/', twitter_callback_sso, name='twitter_callback'),
    path('accounts/login/', CustomLoginView.as_view(), name='super_user_login'),
    path('accounts/logout/', CustomLogoutView.as_view(), name='super_user_logout'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('healthz', health_check, name='health_check'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.post.urls', namespace='post')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    ) + static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

mytwitterbot/mytwitterbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/about_us.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

{% block about_us %}
    <section class="d-flex flex-column-reverse flex-md-row position-relative">
        <div class="d-flex flex-column justify-content-end main-text-container position-absolute w-100 h-100">
            <div class="text-content py-4">
                <h1 class="text-primary main-text-header ps-5 pe-4 ">
                    {% trans "Who we are" %} ؟
                </h1>

                <p class="px-3 mt-5 ">
                    {% trans "Our project is a support for the original Campaign On Twitter" %}
                <p class="px-3 mt-3 ">
                    <b> {% trans "What is the campaign" %} ؟</b>
                </p>

                <p class="px-3 mt-3 ">
                    {% trans "An awareness campaign aimed at stopping the aggression on Gaza and lifting the blockade through exposing Zionist media manipulation by posting tweets in English on Twitter and revealing the facts to the Western and Arab world about what is happening in Gaza" %}
                </p>

            </div>
        </div>
        <div class="main-image-container">
            <img class="w-100" style="height:100vh" src="{% static '/images/about-us-cover.jpg' %}" alt="Image"/>
        </div>
    </section>
{% endblock %}

apps/templates/base.html
{% load i18n %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% trans "Resist" %}</title>
    <link href='https://fonts.googleapis.com/css?family=Almarai' rel='stylesheet'>
    <link href="{% static '/css/base.css' %}" rel="stylesheet">
    <link href="{% static '/css/index.css' %}" rel="stylesheet">
    <link href="{% static '/css/header.css' %}" rel="stylesheet">
    <link href="{% static '/css/about_us.css' %}" rel="stylesheet">
</head>
<body dir="rtl">
{% include 'header.html' %}
{% block content %}
    {% block welcome_page %}

    {% endblock %}
    {% block login_page %}

    {% endblock %}
    {% if user.is_authenticated %}
        {% block post_to_twitter %}

        {% endblock %}
    {% endif %}
    {% block about_us %}

    {% endblock %}
{% endblock %}
</body>
</html>

apps/templates/header.html
{% load i18n %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <img class="navbar-brand" width="48px" src="{% static '/images/logo.svg' %}" alt="Your Logo"/>
        <img class="navbar-brand mx-2" width="48px" src="{% static '/images/logo-text.svg' %}" alt="Your Logo"/>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <div class="d-flex w-100 justify-content-between flex-column flex-md-row">
                <div class="d-flex"></div>
                <ul class="navbar-nav mb-2 mb-lg-0 px-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="{% url 'post:welcome_page' %}">{% trans "Home" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mx-md-5 active" href="{% url 'post:about_us' %}">{% trans "About Us" %}</a>
                    </li>
                </ul>
                <form class="d-flex">
                    {% if not request.user.is_authenticated %}
                    <a href="{% url 'post:super_user_login' %}"
                       class="btn btn-primary mx-3 d-flex align-items-center">{% trans "Login" %}</a>
                    {% else %}
                        <a href="{% url 'post:super_user_logout' %}"
                           class="btn btn-outline-primary ms-3  d-flex align-items-center">{% trans "Logout" %}</a>
                    {% endif %}
                    {% if request.user.is_authenticated and request.user.is_superuser %}
                        <a href="{% url 'post:post_to_twitter' %}"
                           class="btn btn-primary ms-5  d-flex align-items-center">{% trans "Post Tweet" %}</a>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</nav>

apps/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block welcome_page %}
    <section class="d-flex flex-column-reverse flex-md-row">
        <div class="d-flex flex-column main-text-container py-5">
            <h1 class="text-primary main-text-header ps-5 pe-4 ">
                {% trans "In support of Palestine Resist as much as you can" %}
            </h1>
            <p class="px-3 mt-5 h6">
                {% trans "Resist it's an awareness campaign on" %}
                <u><b>{% trans "Twitter" %}</b></u>
                {% trans "that springs from the depths of our hearts to change the narrative and expose deception" %}
            </p>

            <p class="px-3 mt-3 h6">
                {% trans "If you're ready to participate in this effort" %}
                <u><b>{% trans "you have the opportunity now" %}</b></u>
            </p>

            <p class="px-3 mt-3 h6">
                {% trans "Join us by clicking the button below Resist" %}
                <b>{% trans "and we will share the facts in your voices in foreign languages to make the world hear us" %}</b>
            </p>

            <p class="px-3 mt-3 h6">
                {% trans "Get started and be a part of this creative campaign" %}
            </p>

            <div class="px-3 mt-3 h6">
                <table class="d-flex text-primary">
                    <tbody>
                    <tr>
                        <td class="ps-4"><p>{% trans "Number of Resistants" %} :</p></td>
                        <td><p>{{ resistants_count }}</p></td>
                    </tr>
                    <tr>
                        <td><p>{% trans "Number of tweets" %} :</p></td>
                        <td><p>{{ tweets_count }}</p></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            {% if not request.user.is_authenticated %}
                <a href="{% url 'post:twitter_login' %}" class="btn btn-primary mx-3 align-self-start px-4">
                    {% trans "Resist" %}
                    <img src="{% static '/images/twitter.svg' %}" width="15px" alt="" srcset="">
                </a>
            {% endif %}
        </div>
        <div class="main-image-container">
            <img class="w-100" src="{% static '/images/main-page.png' %}" alt="Image"/>
        </div>
    </section>
{% endblock %}

apps/templates/login.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load i18n %}

{% block login_page %}
    <div class="col-md-6">
        <div class="text-center">
            <h2> {% trans "sign in with twitter" %} </h2>
            {% buttons %}
                <a href="{% url 'post:twitter_login' %}" class="btn btn-primary"> {% trans "Go To Twitter" %} </a>
            {% endbuttons %}
        </div>
    </div>
{% endblock %}

apps/templates/post_to_twitter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap5 %}
{% load i18n %}

{% block post_to_twitter %}
    <div class="col-md-6">
        <form method="post" action="{% url 'post:post_to_twitter' %}" enctype="multipart/form-data" class="my-form">
            {% csrf_token %}
            <div class="mb-3">
                {{ form|crispy }}
            </div>
            {% buttons %}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                </div>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}